### PR TITLE
Validation errors serializer

### PR DESCRIPTION
**Pull request by phndiaye**
Related to #8

### CODE REVIEW

**Comment by phndiaye** [comment]
About the returned payload. Here is the story. Let me know what you think.

Discovered some Ember magic the last day! When an error occurs on a model saving, its errored attributes are automatically filled with errors (of course if Ember receives a payload in its expected formatting). For example, if the API returns (on `.save`) the following payload:

```
{
  user: {
    errors: {
      email: [blank,not_good],
      password: [too_short],
    }
  }
}
```

The `user` model will have its errors fields populated as:
`user.errors.email = [blank,not_good]`

Then forms can directly iterate over `user.errors.[field]`

**Comment by tgallice** [comment]
Look good ! What's happen when its a embed model which fail ?

**Comment by phndiaye** [comment]
@tgallice I was going to add more tests in identity-server for example to test the cases

**Review by AlexisMontagne — APPROVED** [review]
LGTM 👍

**Pull request merged**
